#!/bin/sh
#
# Script that will start a process, and then restart (kill and start it again)
# after a set amount of time.  Default it 120 minutes. Default signal is -9
#
# The format of the time follows the format of sleep.
#
# Default kill command is kill, another is pkill which will kill the process
# and subprocesses.
#
# ./aviewtoakill command [time] [signal] [kill command]

cleanup() {
  sleep 1s
  echo
  echo "Last pid: " $pid
  result=`ps -q $pid`
  if [ "$?" -ne 0 ]; then
    echo "No process remaining"
  else
    echo "Process still running: " $result
  fi
  exit
}

trap 'cleanup' 2

pid=0
command=$1
if [ -z $command ]; then
  echo $0 "command [time] [signal] [kill command]"
  exit 1
fi
sleep=""
signal=""
kill=""
if [ -z $2 ]; then
  sleep="120m"
else
  sleep=$2
fi
if [ -z $3 ]; then
  signal="-9"
else
  signal=$3
fi
if [ -z $4 ]; then
  kill="kill"
else
  kill=$4
fi
while :
do
  if [ $pid -ne 0 ]; then
    echo "kill pid is " $pid
    $kill $signal $pid
    sleep 5s
  fi
  $command &
  pid=$!
  sleep $sleep
done
