#!/bin/sh
#
# Script that will start a process, and then restart (kill and start it again)
# after a set amount of time.  Default it 120 minutes. Default signal is -9
#
# The format of the time follows the format of sleep.
#
# ./aviewtoakill command [time] [signal]

cleanup() {
  sleep 1s
  echo
  echo "Last pid: " $pid
  result=`ps -q $pid`
  if [ "$?" -ne 0 ]; then 
    echo "No process remaining"
  fi
  exit
}

trap 'cleanup' 2

pid=0
command=$1
sleep=""
signal=""
if [ -z $2 ]; then
  sleep="120m"
else
  sleep=$2
fi
if [ -z $3 ]; then
  signal="-9"
else
  signal=$3
fi
while :
do
  if [ $pid -ne 0 ]; then
    echo "kill pid is " $pid
    kill $signal $pid
    sleep 5s
  fi
  $command &
  pid=$!
  sleep $sleep
done
